from datetime import datetime


PRIORITY_PREP_BLOCK = """Compete with past contests, participate in virtual contests in the late 2022 or early 2023, especially 2022 all contests and 2023 first six months contests. And apart from that, you can prepare previous year questions of system design by adding AI features and behavioral questions.

And you can add, you did a lot of ML, GenAI, text classification, text summarization, graph ML, genome-based recommendation, collaborative and content-based filtering, and then genome-based recommendation. Python, Flask, FastAPI, Golang, low latency, concurrency, strictly typed, and Kafka Redis, LLMOps, Kubernetes, Docker, speech-to-text, GCP, AWS, Microsoft Azure Foundry models, region selection and all. AWS OpenSearch, Cohere, re-ranking, prompt engineering, prompt management and creation and refinement. Langra agents, LangChain for conversational chains, maintaining and memory, clustering, re-ranking, RAG, fine-tuning using LoRA and QLoRA, AI evaluation and observability.

I think that good problem-solving skills and knowledge about what we are building can increase the time to, can decrease the time and increase the speed to review what AI has generated, since manual review is mandatory if something is going to production. Because there are cases where an entire AWS region was down due to not properly reviewing the code generated by AI before pushing it to production.

After Aug 15 take anything np
"""


SHARED_REMINDER = """Every block also carries the daily baseline:
- Revise Striver A2Z for 1 hour today.
- Apply to jobs on LinkedIn, email, Instahyre, Naukri, and similar platforms.
- Message at least 5 recruiters properly on LinkedIn or relevant hiring platforms.
- Complete the ML / Kaggle / GenAI / Hugging Face / research / ML competitions block.
- On Saturday or Sunday, complete 1 CodeChef question for the weekly DSA add-on.
"""


MOTIVATION_MESSAGE = """Keep doing it daily without missing even one day. The consistency will be exponentially beneficial after a few months.
"""


JOB_DEFINITIONS = {
    "morning_dsa": {
        "schedule": "Daily at 8:00 AM IST",
        "subject": "8 AM DSA Block: 1 CF 1700+ + 1 LC Medium+",
        "body": """Complete this DSA block:
- 1 Codeforces 1700+ question.
- 1 LeetCode Medium+ question.

Start clean, keep the timer honest, and mark this first DSA block in the tracker after you finish.
""",
    },
    "evening_dsa": {
        "schedule": "Daily at 8:00 PM IST",
        "subject": "8 PM DSA Block: 1 CF 1700+ + 1 LC Medium+",
        "body": """Complete this DSA block:
- 1 Codeforces 1700+ question.
- 1 LeetCode Medium+ question.

Finish the second DSA block and update the tracker honestly.
""",
    },
    "behavioral_prep": {
        "schedule": "Daily at 9:30 PM IST",
        "subject": "9:30 PM Behavioral Prep: 30 minutes with AI and internet resources",
        "body": """Now spend 30 minutes on behavioral interview prep:
- Practice stories using STAR format.
- Use AI for mock questions and feedback.
- Check LinkedIn, Reddit, company blogs, and internet resources for role-specific patterns.

After the session, mark behavioral prep in the tracker.
""",
    },
    "daily_log_reminder": {
        "schedule": "Daily at 10:15 PM IST",
        "subject": "Daily Tracker Reminder: Mark today's progress",
        "body": """Open Prep Tracker and mark what you completed today:
- Both DSA blocks.
- Striver A2Z revision.
- Job applications and recruiter messages.
- ML / Kaggle / GenAI / Hugging Face / research / ML competitions block.
- Behavioral prep.
- Weekend CodeChef question if today is Saturday or Sunday.
- Notes for anything missed.

The point is not to look perfect. The point is to keep the data honest.
""",
    },
    "weekly_resume_start": {
        "schedule": "Every Saturday at 9:00 AM IST",
        "subject": "Saturday Resume Prep: Update this week's resume work",
        "body": """This week's resume-prep task:
- Improve one resume section.
- Add or sharpen project bullets with measurable impact.
- Update LinkedIn/GitHub/portfolio details if needed.
- Save notes about what changed.

Mark resume prep in the tracker when it is complete.
""",
    },
    "weekly_resume_check": {
        "schedule": "Every Sunday at 10:00 PM IST",
        "subject": "Sunday Resume Check: Mark weekly resume prep complete",
        "body": """Before ending the week, open Prep Tracker and mark whether resume prep was completed.

If it was missed, add a note with the blocker so next week starts with clarity.
""",
    },
}


def build_email(job_key, frontend_url):
    if job_key not in JOB_DEFINITIONS:
        raise KeyError(f"Unknown job key: {job_key}")

    job = JOB_DEFINITIONS[job_key]
    today = datetime.now().strftime("%Y-%m-%d")
    text_body = f"""Date: {today}
Schedule: {job["schedule"]}

{job["body"].strip()}

Priority Prep Block:
{PRIORITY_PREP_BLOCK.strip()}

{SHARED_REMINDER.strip()}

Motivation:
{MOTIVATION_MESSAGE.strip()}

Tracker: {frontend_url}
"""
    html_body = text_body.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    html_body = html_body.replace("\n", "<br>")

    return {
        "job_key": job_key,
        "subject": job["subject"],
        "text": text_body,
        "html": f"<div style=\"font-family:Arial,sans-serif;line-height:1.55;color:#111827\">{html_body}</div>",
        "schedule": job["schedule"],
    }
